import { UserPreferences, MovieRecommendation } from './types';

export function getFallbackMovieRecommendations(preferences: UserPreferences): MovieRecommendation[] {
  const { mood, preferredMovieGenre } = preferences;

  const recommendationMap: Record<string, MovieRecommendation[]> = {
    'Relaxing': [
      {
        title: 'My Neighbor Totoro',
        whyItFits: 'A gentle, heartwarming Studio Ghibli film that soothes the soul with its peaceful countryside setting.',
        moodMatch: 'Calming visuals and gentle storytelling create a stress-free experience',
        timeFit: 'Perfect runtime at 86 minutes for a relaxing evening',
        platformFit: 'Available on HBO Max and streaming services',
        similarMovies: ['Kiki\'s Delivery Service', 'Ponyo', 'The Secret World of Arrietty'],
        confidence: 96,
        year: 1988,
      },
      {
        title: 'Chef',
        whyItFits: 'Feel-good movie about rediscovering passion through food and family.',
        moodMatch: 'Uplifting and warm without any stress or conflict',
        timeFit: 'Comfortable 114-minute runtime',
        platformFit: 'Available on Netflix and Amazon Prime',
        similarMovies: ['Julie & Julia', 'The Hundred-Foot Journey', 'Ratatouille'],
        confidence: 93,
        year: 2014,
      },
      {
        title: 'Amélie',
        whyItFits: 'Whimsical French film about finding joy in small moments and helping others.',
        moodMatch: 'Charming and visually soothing with gentle humor',
        timeFit: '122 minutes of pure delight',
        platformFit: 'Available on various streaming platforms',
        similarMovies: ['Midnight in Paris', 'The Grand Budapest Hotel', 'Big Fish'],
        confidence: 91,
        year: 2001,
      },
    ],
    'Cozy': [
      {
        title: 'The Grand Budapest Hotel',
        whyItFits: 'Wes Anderson\'s visually stunning tale with warmth, humor, and impeccable aesthetics.',
        moodMatch: 'Cozy color palette and charming storytelling',
        timeFit: 'Perfectly paced at 99 minutes',
        platformFit: 'Available on Disney+ and streaming services',
        similarMovies: ['Moonrise Kingdom', 'The French Dispatch', 'Amélie'],
        confidence: 95,
        year: 2014,
      },
      {
        title: 'Little Women',
        whyItFits: 'Heartwarming story of sisterhood, family, and finding your place in the world.',
        moodMatch: 'Warm, intimate, and emotionally comforting',
        timeFit: '135 minutes of cozy period drama',
        platformFit: 'Available on Netflix and Amazon Prime',
        similarMovies: ['Pride and Prejudice', 'Emma', 'Sense and Sensibility'],
        confidence: 94,
        year: 2019,
      },
      {
        title: 'Paddington 2',
        whyItFits: 'Pure wholesome joy with a lovable bear spreading kindness.',
        moodMatch: 'Impossibly cozy and heartwarming',
        timeFit: 'Delightful 103 minutes',
        platformFit: 'Available on HBO Max and streaming',
        similarMovies: ['Paddington', 'Wallace & Gromit', 'Fantastic Mr. Fox'],
        confidence: 92,
        year: 2017,
      },
    ],
    'Competitive': [
      {
        title: 'Rush',
        whyItFits: 'Intense rivalry between Formula 1 racers in the 1970s with high-stakes competition.',
        moodMatch: 'Adrenaline-fueled competitive spirit',
        timeFit: '123 minutes of edge-of-your-seat racing',
        platformFit: 'Available on Netflix and Amazon Prime',
        similarMovies: ['Ford v Ferrari', 'Senna', 'Grand Prix'],
        confidence: 96,
        year: 2013,
      },
      {
        title: 'Moneyball',
        whyItFits: 'Strategic competition in baseball using analytics to beat bigger teams.',
        moodMatch: 'Intellectual competition and underdog triumph',
        timeFit: '133 minutes of strategic gameplay',
        platformFit: 'Available on various streaming platforms',
        similarMovies: ['The Social Network', 'Steve Jobs', 'The Big Short'],
        confidence: 93,
        year: 2011,
      },
      {
        title: 'Whiplash',
        whyItFits: 'Intense psychological battle between a drummer and his ruthless instructor.',
        moodMatch: 'Raw competitive drive and pursuit of perfection',
        timeFit: 'Gripping 106 minutes',
        platformFit: 'Available on Netflix and streaming',
        similarMovies: ['Black Swan', 'The Wrestler', 'Birdman'],
        confidence: 94,
        year: 2014,
      },
    ],
    'Story-driven': [
      {
        title: 'The Shawshank Redemption',
        whyItFits: 'Masterful storytelling about hope, friendship, and redemption over decades.',
        moodMatch: 'Deeply moving narrative with powerful character arcs',
        timeFit: '142 minutes of cinematic perfection',
        platformFit: 'Available on Netflix and streaming services',
        similarMovies: ['The Green Mile', 'Forrest Gump', 'The Godfather'],
        confidence: 98,
        year: 1994,
      },
      {
        title: 'Arrival',
        whyItFits: 'Thought-provoking sci-fi about communication, time, and human connection.',
        moodMatch: 'Cerebral storytelling with emotional depth',
        timeFit: '116 minutes of intelligent narrative',
        platformFit: 'Available on Amazon Prime and streaming',
        similarMovies: ['Interstellar', 'Blade Runner 2049', 'Her'],
        confidence: 95,
        year: 2016,
      },
      {
        title: 'Parasite',
        whyItFits: 'Brilliant social commentary with unpredictable twists and masterful storytelling.',
        moodMatch: 'Gripping narrative that keeps you engaged',
        timeFit: '132 minutes of cinematic excellence',
        platformFit: 'Available on Hulu and streaming',
        similarMovies: ['Memories of Murder', 'Burning', 'Shoplifters'],
        confidence: 97,
        year: 2019,
      },
    ],
    'Strategic': [
      {
        title: 'The Prestige',
        whyItFits: 'Intricate tale of rival magicians with layers of deception and strategy.',
        moodMatch: 'Complex plotting and intellectual engagement',
        timeFit: '130 minutes of mind-bending twists',
        platformFit: 'Available on various streaming platforms',
        similarMovies: ['Inception', 'Memento', 'Shutter Island'],
        confidence: 96,
        year: 2006,
      },
      {
        title: 'Ocean\'s Eleven',
        whyItFits: 'Stylish heist film with elaborate planning and execution.',
        moodMatch: 'Strategic thinking and clever problem-solving',
        timeFit: '116 minutes of slick entertainment',
        platformFit: 'Available on HBO Max and streaming',
        similarMovies: ['The Italian Job', 'Now You See Me', 'Logan Lucky'],
        confidence: 94,
        year: 2001,
      },
      {
        title: 'The Imitation Game',
        whyItFits: 'Code-breaking genius working to outsmart Nazi encryption during WWII.',
        moodMatch: 'Intellectual strategy and problem-solving',
        timeFit: '114 minutes of historical intrigue',
        platformFit: 'Available on Netflix and streaming',
        similarMovies: ['A Beautiful Mind', 'The Theory of Everything', 'Hidden Figures'],
        confidence: 92,
        year: 2014,
      },
    ],
    'Chaotic': [
      {
        title: 'Everything Everywhere All at Once',
        whyItFits: 'Multiverse-hopping madness with emotional depth and pure creative chaos.',
        moodMatch: 'Beautifully chaotic with constant surprises',
        timeFit: '139 minutes of wild creativity',
        platformFit: 'Available on various streaming platforms',
        similarMovies: ['Spider-Man: Into the Spider-Verse', 'The Matrix', 'Scott Pilgrim'],
        confidence: 97,
        year: 2022,
      },
      {
        title: 'Mad Max: Fury Road',
        whyItFits: 'Non-stop action spectacle with incredible practical effects and pure adrenaline.',
        moodMatch: 'Relentless chaotic energy from start to finish',
        timeFit: '120 minutes of high-octane mayhem',
        platformFit: 'Available on HBO Max and streaming',
        similarMovies: ['John Wick', 'The Raid', 'Baby Driver'],
        confidence: 95,
        year: 2015,
      },
      {
        title: 'Scott Pilgrim vs. the World',
        whyItFits: 'Video game-inspired visual chaos with humor, romance, and epic battles.',
        moodMatch: 'Energetic, colorful, and delightfully chaotic',
        timeFit: '112 minutes of pure fun',
        platformFit: 'Available on Netflix and streaming',
        similarMovies: ['Kick-Ass', 'Guardians of the Galaxy', 'The Lego Movie'],
        confidence: 93,
        year: 2010,
      },
    ],
  };

  let recommendations = recommendationMap[mood] || recommendationMap['Relaxing'];

  if (preferredMovieGenre && preferredMovieGenre !== 'No preference') {
    recommendations = recommendations.map(rec => ({
      ...rec,
      confidence: rec.confidence - 5,
    }));
  }

  return recommendations;
}
