export interface MovieDataItem {
  id: string;
  title: string;
  year?: number;
  moods: string[];
  genres: string[];
  watchStyles: string[];
  timeFits: string[];
  avoidTags: string[];
  contentTone: string;
  similarTitles: string[];
}

export const movieDataset: MovieDataItem[] = [
  {
    id: 'paddington-2',
    title: 'Paddington 2',
    year: 2017,
    moods: ['Comforting', 'Funny', 'Relaxing', 'Cozy'],
    genres: ['Comedy'],
    watchStyles: ['Light', 'Family-friendly'],
    timeFits: ['About 1 hour', 'Several hours', 'About 2 hours'],
    avoidTags: [],
    contentTone: 'Heartwarming and wholesome',
    similarTitles: ['Paddington', 'Fantastic Mr. Fox', 'The Grand Budapest Hotel'],
  },
  {
    id: 'spider-verse',
    title: 'Spider-Man: Into the Spider-Verse',
    year: 2018,
    moods: ['Chaotic', 'Competitive', 'Story-driven'],
    genres: ['Animation', 'Action'],
    watchStyles: ['Engaging', 'Visually stunning'],
    timeFits: ['About 1 hour', 'Several hours', 'About 2 hours'],
    avoidTags: ['violence'],
    contentTone: 'Energetic and inspiring',
    similarTitles: ['The Mitchells vs. The Machines', 'Big Hero 6', 'Raya and the Last Dragon'],
  },
  {
    id: 'grand-budapest-hotel',
    title: 'The Grand Budapest Hotel',
    year: 2014,
    moods: ['Cozy', 'Story-driven', 'Relaxing'],
    genres: ['Comedy', 'Drama'],
    watchStyles: ['Artistic', 'Quirky'],
    timeFits: ['About 1 hour', 'Several hours', 'About 2 hours'],
    avoidTags: ['violence'],
    contentTone: 'Whimsical and stylized',
    similarTitles: ['Fantastic Mr. Fox', 'Moonrise Kingdom', 'The French Dispatch'],
  },
  {
    id: 'knives-out',
    title: 'Knives Out',
    year: 2019,
    moods: ['Strategic', 'Story-driven'],
    genres: ['Thriller', 'Comedy'],
    watchStyles: ['Engaging', 'Clever'],
    timeFits: ['Several hours', 'About 2 hours'],
    avoidTags: ['violence'],
    contentTone: 'Witty and entertaining',
    similarTitles: ['Glass Onion', 'Murder on the Orient Express', 'Clue'],
  },
  {
    id: 'spirited-away',
    title: 'Spirited Away',
    year: 2001,
    moods: ['Story-driven', 'Cozy', 'Relaxing'],
    genres: ['Animation'],
    watchStyles: ['Artistic', 'Immersive'],
    timeFits: ['About 1 hour', 'Several hours', 'About 2 hours'],
    avoidTags: [],
    contentTone: 'Magical and contemplative',
    similarTitles: ["Howl's Moving Castle", 'Princess Mononoke', 'My Neighbor Totoro'],
  },
  {
    id: 'interstellar',
    title: 'Interstellar',
    year: 2014,
    moods: ['Story-driven', 'Strategic'],
    genres: ['Sci-Fi', 'Drama'],
    watchStyles: ['Epic', 'Immersive'],
    timeFits: ['Several hours'],
    avoidTags: [],
    contentTone: 'Grand and emotional',
    similarTitles: ['Arrival', 'Gravity', 'The Martian'],
  },
  {
    id: 'everything-everywhere',
    title: 'Everything Everywhere All at Once',
    year: 2022,
    moods: ['Chaotic', 'Story-driven'],
    genres: ['Sci-Fi', 'Comedy', 'Drama'],
    watchStyles: ['Mind-bending', 'Unique'],
    timeFits: ['Several hours'],
    avoidTags: ['violence'],
    contentTone: 'Chaotic and heartfelt',
    similarTitles: ['Swiss Army Man', 'Eternal Sunshine', 'The Matrix'],
  },
  {
    id: 'little-women',
    title: 'Little Women',
    year: 2019,
    moods: ['Cozy', 'Story-driven', 'Relaxing'],
    genres: ['Drama', 'Romance'],
    watchStyles: ['Period piece', 'Character-driven'],
    timeFits: ['Several hours', 'About 2 hours'],
    avoidTags: [],
    contentTone: 'Warm and nostalgic',
    similarTitles: ['Pride and Prejudice', 'Emma', 'Sense and Sensibility'],
  },
  {
    id: 'the-martian',
    title: 'The Martian',
    year: 2015,
    moods: ['Strategic', 'Story-driven'],
    genres: ['Sci-Fi', 'Drama'],
    watchStyles: ['Problem-solving', 'Optimistic'],
    timeFits: ['Several hours', 'About 2 hours'],
    avoidTags: [],
    contentTone: 'Hopeful and clever',
    similarTitles: ['Interstellar', 'Gravity', 'Apollo 13'],
  },
  {
    id: 'coco',
    title: 'Coco',
    year: 2017,
    moods: ['Cozy', 'Story-driven', 'Relaxing'],
    genres: ['Animation'],
    watchStyles: ['Family-friendly', 'Colorful'],
    timeFits: ['About 1 hour', 'Several hours', 'About 2 hours'],
    avoidTags: [],
    contentTone: 'Heartwarming and vibrant',
    similarTitles: ['Encanto', 'Moana', 'Soul'],
  },
  {
    id: 'whiplash',
    title: 'Whiplash',
    year: 2014,
    moods: ['Competitive', 'Story-driven'],
    genres: ['Drama'],
    watchStyles: ['Intense', 'Musical'],
    timeFits: ['About 1 hour', 'Several hours'],
    avoidTags: [],
    contentTone: 'Raw competitive drive',
    similarTitles: ['Black Swan', 'The Wrestler', 'Birdman'],
  },
  {
    id: 'parasite',
    title: 'Parasite',
    year: 2019,
    moods: ['Strategic', 'Story-driven'],
    genres: ['Thriller', 'Drama'],
    watchStyles: ['Intense', 'Unpredictable'],
    timeFits: ['Several hours'],
    avoidTags: ['violence'],
    contentTone: 'Dark and gripping',
    similarTitles: ['Memories of Murder', 'Burning', 'The Handmaiden'],
  },
  {
    id: 'fantastic-mr-fox',
    title: 'Fantastic Mr. Fox',
    year: 2009,
    moods: ['Cozy', 'Relaxing'],
    genres: ['Animation', 'Comedy'],
    watchStyles: ['Quirky', 'Artistic'],
    timeFits: ['Under 30 minutes', 'About 1 hour'],
    avoidTags: [],
    contentTone: 'Charming and witty',
    similarTitles: ['The Grand Budapest Hotel', 'Isle of Dogs', 'Paddington'],
  },
  {
    id: 'mad-max-fury-road',
    title: 'Mad Max: Fury Road',
    year: 2015,
    moods: ['Chaotic', 'Competitive'],
    genres: ['Action'],
    watchStyles: ['Adrenaline', 'Visually stunning'],
    timeFits: ['About 1 hour', 'Several hours'],
    avoidTags: ['violence'],
    contentTone: 'Relentless chaotic energy',
    similarTitles: ['John Wick', 'The Raid', 'Baby Driver'],
  },
  {
    id: 'arrival',
    title: 'Arrival',
    year: 2016,
    moods: ['Story-driven', 'Strategic'],
    genres: ['Sci-Fi', 'Drama'],
    watchStyles: ['Cerebral', 'Slow-burn'],
    timeFits: ['About 1 hour', 'Several hours'],
    avoidTags: [],
    contentTone: 'Contemplative and moving',
    similarTitles: ['Interstellar', 'Contact', 'Blade Runner 2049'],
  },
  {
    id: 'soul',
    title: 'Soul',
    year: 2020,
    moods: ['Cozy', 'Story-driven', 'Relaxing'],
    genres: ['Animation'],
    watchStyles: ['Philosophical', 'Artistic'],
    timeFits: ['About 1 hour', 'Several hours'],
    avoidTags: [],
    contentTone: 'Contemplative and uplifting',
    similarTitles: ['Inside Out', 'Coco', 'WALL-E'],
  },
];
