/**
 * FILE: TasteProfile.tsx
 * PURPOSE: Display user's taste profile generated by AI
 * 
 * FEATURES:
 * - Shows AI-generated summary
 * - Displays primary mood
 * - Shows preferred experience
 * - Lists avoid patterns
 * - Professional card design
 * 
 * DEPENDENCIES:
 * - types.ts (TasteProfile)
 * 
 * USED BY:
 * - page.tsx (displayed with results)
 * 
 * STATUS: Complete
 * DO NOT MODIFY: No - Can be updated for UI improvements
 */

'use client';

import { TasteProfile as TasteProfileType } from '@/lib/types';

interface TasteProfileProps {
  profile: TasteProfileType;
}

export default function TasteProfile({ profile }: TasteProfileProps) {
  return (
    <div className="bg-gray-900 rounded-lg border border-gray-800 p-6 mb-8">
      <h3 className="text-xl font-bold text-white mb-4">Your Taste Profile</h3>
      
      <div className="space-y-4">
        <div>
          <p className="text-gray-300 leading-relaxed">{profile.summary}</p>
        </div>

        <div className="grid md:grid-cols-3 gap-4 pt-4 border-t border-gray-800">
          <div>
            <div className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">
              Primary Mood
            </div>
            <div className="text-sm text-white font-medium">
              {profile.primaryMood}
            </div>
          </div>

          <div>
            <div className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">
              Preferred Experience
            </div>
            <div className="text-sm text-white font-medium">
              {profile.preferredExperience}
            </div>
          </div>

          <div>
            <div className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">
              Avoid Pattern
            </div>
            <div className="text-sm text-white font-medium">
              {profile.avoidPattern}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
