/**
 * FILE: TasteProfile.tsx
 * PURPOSE: Display user's taste profile generated by AI
 * 
 * FEATURES:
 * - Shows AI-generated summary
 * - Displays primary mood
 * - Shows preferred experience
 * - Lists avoid patterns
 * - Professional card design
 * 
 * DEPENDENCIES:
 * - types.ts (TasteProfile)
 * 
 * USED BY:
 * - page.tsx (displayed with results)
 * 
 * STATUS: Complete
 * DO NOT MODIFY: No - Can be updated for UI improvements
 */

'use client';

import { TasteProfile as TasteProfileType } from '@/lib/types';

interface TasteProfileProps {
  profile: TasteProfileType;
}

export default function TasteProfile({ profile }: TasteProfileProps) {
  return (
    <div className="bg-night-900 rounded-3xl border border-night-700 p-6 mb-8">
      <h3 className="text-lg font-serif font-bold text-cream-50 mb-3">
        Here&apos;s what I&apos;m reading from you
      </h3>
      
      <div className="space-y-4">
        <div>
          <p className="text-cream-200 leading-relaxed font-serif italic text-sm">{profile.summary}</p>
        </div>

        <div className="grid md:grid-cols-3 gap-4 pt-4 border-t border-night-700">
          <div>
            <div className="text-xs font-medium text-cream-400/60 uppercase tracking-wider mb-1">
              Mood
            </div>
            <div className="text-sm text-cream-100 font-medium">
              {profile.primaryMood}
            </div>
          </div>

          <div>
            <div className="text-xs font-medium text-cream-400/60 uppercase tracking-wider mb-1">
              Vibe
            </div>
            <div className="text-sm text-cream-100 font-medium">
              {profile.preferredExperience}
            </div>
          </div>

          <div>
            <div className="text-xs font-medium text-cream-400/60 uppercase tracking-wider mb-1">
              Steering clear of
            </div>
            <div className="text-sm text-cream-100 font-medium">
              {profile.avoidPattern}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
